# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html


twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    # ...
    configs:
        main_config:
            resize:
                - heigt: 500
                - width: 1000
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
